package com.xftxyz.rocketblog.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.xftxyz.rocketblog.pojo.BlogInfo;
import com.xftxyz.rocketblog.pojo.BlogInfoExample;

public interface BlogInfoMapper {
    // 获取热门博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "LEFT JOIN t_like ON v_bloginfo.blog_id = t_like.blog_id " +
            "LEFT JOIN t_bookmark ON v_bloginfo.blog_id = t_bookmark.blog_id " +
            "LEFT JOIN t_comment ON v_bloginfo.blog_id = t_comment.blog_id " +
            "GROUP BY v_bloginfo.blog_id " +
            "ORDER BY COUNT( DISTINCT t_like.userid )+ COUNT( DISTINCT t_bookmark.userid )+ COUNT( DISTINCT t_comment.comment_id ) DESC")
    List<BlogInfo> selectHotBlogs();

    // 获取点赞最多的博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "LEFT JOIN t_like ON v_bloginfo.blog_id = t_like.blog_id " +
            "GROUP BY v_bloginfo.blog_id " +
            "ORDER BY COUNT( DISTINCT t_like.userid ) DESC")
    List<BlogInfo> selectMostLikeBlogs();

    // 获取收藏最多的博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "LEFT JOIN t_bookmark ON v_bloginfo.blog_id = t_bookmark.blog_id " +
            "GROUP BY v_bloginfo.blog_id " +
            "ORDER BY COUNT( DISTINCT t_bookmark.userid ) DESC")
    List<BlogInfo> selectMostCollectBlogs();

    // 获取评论最多的博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "LEFT JOIN t_comment ON v_bloginfo.blog_id = t_comment.blog_id " +
            "GROUP BY v_bloginfo.blog_id " +
            "ORDER BY COUNT( DISTINCT t_comment.comment_id ) DESC")
    List<BlogInfo> selectMostCommentBlogs();

    // 获取收藏的博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "LEFT JOIN t_bookmark ON v_bloginfo.blog_id = t_bookmark.blog_id " +
            "WHERE t_bookmark.userid = #{userid}")
    List<BlogInfo> selectCollectBlogs(@Param("userid") Long userid);

    // 获取点赞的博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "LEFT JOIN t_like ON v_bloginfo.blog_id = t_like.blog_id " +
            "WHERE t_like.userid = #{userid}")
    List<BlogInfo> selectLikeBlogs(@Param("userid") Long userid);

    // 获取关注的所有人的博客
    @Select("SELECT v_bloginfo.* " +
            "FROM v_bloginfo " +
            "JOIN ( " +
            "SELECT userid_followed " +
            "FROM t_follow " +
            "WHERE userid_following = #{userid} " +
            ") f ON v_bloginfo.userid = f.userid_followed")
    List<BlogInfo> selectFollowBlogs(@Param("userid") Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    long countByExample(BlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int deleteByExample(BlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int insert(BlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int insertSelective(BlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    List<BlogInfo> selectByExample(BlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExampleSelective(@Param("record") BlogInfo record, @Param("example") BlogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_bloginfo
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExample(@Param("record") BlogInfo record, @Param("example") BlogInfoExample example);
}