package com.xftxyz.rocketblog.mapper;

import com.xftxyz.rocketblog.pojo.BlogDetail;
import com.xftxyz.rocketblog.pojo.BlogDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    long countByExample(BlogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int deleteByExample(BlogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int insert(BlogDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int insertSelective(BlogDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    List<BlogDetail> selectByExampleWithBLOBs(BlogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    List<BlogDetail> selectByExample(BlogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExampleSelective(@Param("record") BlogDetail record, @Param("example") BlogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") BlogDetail record, @Param("example") BlogDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogdetail
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExample(@Param("record") BlogDetail record, @Param("example") BlogDetailExample example);
}