package com.xftxyz.rocketblog.mapper;

import com.xftxyz.rocketblog.pojo.BlogWithUser;
import com.xftxyz.rocketblog.pojo.BlogWithUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogWithUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    long countByExample(BlogWithUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    int deleteByExample(BlogWithUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    int insert(BlogWithUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    int insertSelective(BlogWithUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    List<BlogWithUser> selectByExampleWithBLOBs(BlogWithUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    List<BlogWithUser> selectByExample(BlogWithUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    int updateByExampleSelective(@Param("record") BlogWithUser record, @Param("example") BlogWithUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") BlogWithUser record, @Param("example") BlogWithUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_blogwithuser
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    int updateByExample(@Param("record") BlogWithUser record, @Param("example") BlogWithUserExample example);
}