package com.xftxyz.rocketblog.mapper;

import com.xftxyz.rocketblog.pojo.Follow;
import com.xftxyz.rocketblog.pojo.FollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    long countByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int deleteByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int deleteByPrimaryKey(Long followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int insert(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int insertSelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    List<Follow> selectByExample(FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    Follow selectByPrimaryKey(Long followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int updateByExampleSelective(@Param("record") Follow record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int updateByExample(@Param("record") Follow record, @Param("example") FollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int updateByPrimaryKeySelective(Follow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    int updateByPrimaryKey(Follow record);
}