package com.xftxyz.rocketblog.mapper;

import com.xftxyz.rocketblog.pojo.VChat;
import com.xftxyz.rocketblog.pojo.VChatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    long countByExample(VChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    int deleteByExample(VChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    int insert(VChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    int insertSelective(VChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    List<VChat> selectByExample(VChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    int updateByExampleSelective(@Param("record") VChat record, @Param("example") VChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_chat
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    int updateByExample(@Param("record") VChat record, @Param("example") VChatExample example);
}