package com.xftxyz.rocketblog.mapper;

import com.xftxyz.rocketblog.pojo.VComment;
import com.xftxyz.rocketblog.pojo.VCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    long countByExample(VCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int deleteByExample(VCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int insert(VComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int insertSelective(VComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    List<VComment> selectByExample(VCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExampleSelective(@Param("record") VComment record, @Param("example") VCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_comment
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    int updateByExample(@Param("record") VComment record, @Param("example") VCommentExample example);
}