package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class BlogWithUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.blog_id
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.blog_title
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private String blogTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.userid
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.blog_status
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private Integer blogStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.create_time
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.update_time
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.cover_image
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private String coverImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.username
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.avatar
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_blogwithuser.blog_content
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.blog_id
     *
     * @return the value of v_blogwithuser.blog_id
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.blog_id
     *
     * @param blogId the value for v_blogwithuser.blog_id
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.blog_title
     *
     * @return the value of v_blogwithuser.blog_title
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.blog_title
     *
     * @param blogTitle the value for v_blogwithuser.blog_title
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.userid
     *
     * @return the value of v_blogwithuser.userid
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.userid
     *
     * @param userid the value for v_blogwithuser.userid
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.blog_status
     *
     * @return the value of v_blogwithuser.blog_status
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public Integer getBlogStatus() {
        return blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.blog_status
     *
     * @param blogStatus the value for v_blogwithuser.blog_status
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setBlogStatus(Integer blogStatus) {
        this.blogStatus = blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.create_time
     *
     * @return the value of v_blogwithuser.create_time
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.create_time
     *
     * @param createTime the value for v_blogwithuser.create_time
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.update_time
     *
     * @return the value of v_blogwithuser.update_time
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.update_time
     *
     * @param updateTime the value for v_blogwithuser.update_time
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.cover_image
     *
     * @return the value of v_blogwithuser.cover_image
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.cover_image
     *
     * @param coverImage the value for v_blogwithuser.cover_image
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.username
     *
     * @return the value of v_blogwithuser.username
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.username
     *
     * @param username the value for v_blogwithuser.username
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.avatar
     *
     * @return the value of v_blogwithuser.avatar
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.avatar
     *
     * @param avatar the value for v_blogwithuser.avatar
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogwithuser.blog_content
     *
     * @return the value of v_blogwithuser.blog_content
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogwithuser.blog_content
     *
     * @param blogContent the value for v_blogwithuser.blog_content
     *
     * @mbg.generated Sat Apr 01 00:16:22 CST 2023
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }
}