package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class BlogDetail {

    // 额外的字段：点赞
    private Boolean isLike;

    // 额外的字段：收藏
    private Boolean isCollect;

    public Boolean isLike() {
        return isLike;
    }

    public void setLike(Boolean like) {
        isLike = like;
    }

    public Boolean isCollect() {
        return isCollect;
    }

    public void setCollect(Boolean collect) {
        isCollect = collect;
    }

    /**
     * 此字段对应于数据库列v_blogdetail.blog_id
     */
    private Long blogId;

    /**
     * 此字段对应于数据库列v_blogdetail.blog_title
     */
    private String blogTitle;

    /**
     * 此字段对应于数据库列v_blogdetail.userid
     */
    private Long userid;

    /**
     * 此字段对应于数据库列v_blogdetail.username
     */
    private String username;

    /**
     * 此字段对应于数据库列v_blogdetail.avatar
     */
    private String avatar;

    /**
     * 此字段对应于数据库列v_blogdetail.blog_status
     */
    private Integer blogStatus;

    /**
     * 此字段对应于数据库列v_blogdetail.create_time
     */
    private Date createTime;

    /**
     * 此字段对应于数据库列v_blogdetail.update_time
     */
    private Date updateTime;

    /**
     * 此字段对应于数据库列v_blogdetail.cover_image
     */
    private String coverImage;

    /**
     * 此字段对应于数据库列v_blogdetail.like_count
     */
    private Long likeCount;

    /**
     * 此字段对应于数据库列v_blogdetail.comment_count
     */
    private Long commentCount;

    /**
     * 此字段对应于数据库列v_blogdetail.bookmark_count
     */
    private Long bookmarkCount;

    /**
     * 此字段对应于数据库列v_blogdetail.blog_content
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.blog_id
     *
     * @return the value of v_blogdetail.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.blog_id
     *
     * @param blogId the value for v_blogdetail.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.blog_title
     *
     * @return the value of v_blogdetail.blog_title
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.blog_title
     *
     * @param blogTitle the value for v_blogdetail.blog_title
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.userid
     *
     * @return the value of v_blogdetail.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.userid
     *
     * @param userid the value for v_blogdetail.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.username
     *
     * @return the value of v_blogdetail.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.username
     *
     * @param username the value for v_blogdetail.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.avatar
     *
     * @return the value of v_blogdetail.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.avatar
     *
     * @param avatar the value for v_blogdetail.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.blog_status
     *
     * @return the value of v_blogdetail.blog_status
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Integer getBlogStatus() {
        return blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.blog_status
     *
     * @param blogStatus the value for v_blogdetail.blog_status
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBlogStatus(Integer blogStatus) {
        this.blogStatus = blogStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.create_time
     *
     * @return the value of v_blogdetail.create_time
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.create_time
     *
     * @param createTime the value for v_blogdetail.create_time
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.update_time
     *
     * @return the value of v_blogdetail.update_time
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.update_time
     *
     * @param updateTime the value for v_blogdetail.update_time
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.cover_image
     *
     * @return the value of v_blogdetail.cover_image
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.cover_image
     *
     * @param coverImage the value for v_blogdetail.cover_image
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_blogdetail.like_count
     *
     * @return the value of v_blogdetail.like_count
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.like_count
     *
     * @param likeCount the value for v_blogdetail.like_count
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * v_blogdetail.comment_count
     *
     * @return the value of v_blogdetail.comment_count
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.comment_count
     *
     * @param commentCount the value for v_blogdetail.comment_count
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * v_blogdetail.bookmark_count
     *
     * @return the value of v_blogdetail.bookmark_count
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getBookmarkCount() {
        return bookmarkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.bookmark_count
     *
     * @param bookmarkCount the value for v_blogdetail.bookmark_count
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBookmarkCount(Long bookmarkCount) {
        this.bookmarkCount = bookmarkCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * v_blogdetail.blog_content
     *
     * @return the value of v_blogdetail.blog_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_blogdetail.blog_content
     *
     * @param blogContent the value for v_blogdetail.blog_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }
}