package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.comment_content
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.blog_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.createtime
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.userid
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_id
     *
     * @return the value of t_comment.comment_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_id
     *
     * @param commentId the value for t_comment.comment_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.comment_content
     *
     * @return the value of t_comment.comment_content
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.comment_content
     *
     * @param commentContent the value for t_comment.comment_content
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.blog_id
     *
     * @return the value of t_comment.blog_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.blog_id
     *
     * @param blogId the value for t_comment.blog_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createtime
     *
     * @return the value of t_comment.createtime
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createtime
     *
     * @param createtime the value for t_comment.createtime
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.userid
     *
     * @return the value of t_comment.userid
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.userid
     *
     * @param userid the value for t_comment.userid
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}