package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class Follow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.follow_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Long followId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.userid_following
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Long useridFollowing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.userid_followed
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Long useridFollowed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.createtime
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.follow_id
     *
     * @return the value of t_follow.follow_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Long getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.follow_id
     *
     * @param followId the value for t_follow.follow_id
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setFollowId(Long followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.userid_following
     *
     * @return the value of t_follow.userid_following
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Long getUseridFollowing() {
        return useridFollowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.userid_following
     *
     * @param useridFollowing the value for t_follow.userid_following
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setUseridFollowing(Long useridFollowing) {
        this.useridFollowing = useridFollowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.userid_followed
     *
     * @return the value of t_follow.userid_followed
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Long getUseridFollowed() {
        return useridFollowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.userid_followed
     *
     * @param useridFollowed the value for t_follow.userid_followed
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setUseridFollowed(Long useridFollowed) {
        this.useridFollowed = useridFollowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.createtime
     *
     * @return the value of t_follow.createtime
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.createtime
     *
     * @param createtime the value for t_follow.createtime
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}