package com.xftxyz.rocketblog.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FollowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public FollowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFollowIdIsNull() {
            addCriterion("follow_id is null");
            return (Criteria) this;
        }

        public Criteria andFollowIdIsNotNull() {
            addCriterion("follow_id is not null");
            return (Criteria) this;
        }

        public Criteria andFollowIdEqualTo(Long value) {
            addCriterion("follow_id =", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdNotEqualTo(Long value) {
            addCriterion("follow_id <>", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdGreaterThan(Long value) {
            addCriterion("follow_id >", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdGreaterThanOrEqualTo(Long value) {
            addCriterion("follow_id >=", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdLessThan(Long value) {
            addCriterion("follow_id <", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdLessThanOrEqualTo(Long value) {
            addCriterion("follow_id <=", value, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdIn(List<Long> values) {
            addCriterion("follow_id in", values, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdNotIn(List<Long> values) {
            addCriterion("follow_id not in", values, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdBetween(Long value1, Long value2) {
            addCriterion("follow_id between", value1, value2, "followId");
            return (Criteria) this;
        }

        public Criteria andFollowIdNotBetween(Long value1, Long value2) {
            addCriterion("follow_id not between", value1, value2, "followId");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingIsNull() {
            addCriterion("userid_following is null");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingIsNotNull() {
            addCriterion("userid_following is not null");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingEqualTo(Long value) {
            addCriterion("userid_following =", value, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingNotEqualTo(Long value) {
            addCriterion("userid_following <>", value, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingGreaterThan(Long value) {
            addCriterion("userid_following >", value, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingGreaterThanOrEqualTo(Long value) {
            addCriterion("userid_following >=", value, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingLessThan(Long value) {
            addCriterion("userid_following <", value, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingLessThanOrEqualTo(Long value) {
            addCriterion("userid_following <=", value, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingIn(List<Long> values) {
            addCriterion("userid_following in", values, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingNotIn(List<Long> values) {
            addCriterion("userid_following not in", values, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingBetween(Long value1, Long value2) {
            addCriterion("userid_following between", value1, value2, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowingNotBetween(Long value1, Long value2) {
            addCriterion("userid_following not between", value1, value2, "useridFollowing");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedIsNull() {
            addCriterion("userid_followed is null");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedIsNotNull() {
            addCriterion("userid_followed is not null");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedEqualTo(Long value) {
            addCriterion("userid_followed =", value, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedNotEqualTo(Long value) {
            addCriterion("userid_followed <>", value, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedGreaterThan(Long value) {
            addCriterion("userid_followed >", value, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedGreaterThanOrEqualTo(Long value) {
            addCriterion("userid_followed >=", value, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedLessThan(Long value) {
            addCriterion("userid_followed <", value, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedLessThanOrEqualTo(Long value) {
            addCriterion("userid_followed <=", value, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedIn(List<Long> values) {
            addCriterion("userid_followed in", values, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedNotIn(List<Long> values) {
            addCriterion("userid_followed not in", values, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedBetween(Long value1, Long value2) {
            addCriterion("userid_followed between", value1, value2, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andUseridFollowedNotBetween(Long value1, Long value2) {
            addCriterion("userid_followed not between", value1, value2, "useridFollowed");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_follow
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 27 19:37:36 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_follow
     *
     * @mbg.generated Mon Mar 27 19:37:36 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}