package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class VChat {
    /**
     * 消息id
     * 此字段对应于数据库列v_chat.chat_id
     */
    private Long chatId;

    /**
     * 发送方id
     * 此字段对应于数据库列v_chat.userid_from
     */
    private Long useridFrom;

    /**
     * 接收方id
     * 此字段对应于数据库列v_chat.userid_to
     */
    private Long useridTo;

    /**
     * 消息内容
     * 此字段对应于数据库列v_chat.message_content
     */
    private String messageContent;

    /**
     * 消息发送时间
     * 此字段对应于数据库列v_chat.createtime
     */
    private Date createtime;

    /**
     * 发送方用户名
     * 此字段对应于数据库列v_chat.from_username
     */
    private String fromUsername;

    /**
     * 发送方用户头像
     * 此字段对应于数据库列v_chat.from_avatar
     */
    private String fromAvatar;

    /**
     * 接收方用户名
     * 此字段对应于数据库列v_chat.to_username
     */
    private String toUsername;

    /**
     * 接收方用户头像
     * 此字段对应于数据库列v_chat.to_avatar
     */
    private String toAvatar;

    /**
     * 消息是否已读
     * 此字段对应于数据库列v_chat.readed
     */
    private Integer readed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.chat_id
     *
     * @return the value of v_chat.chat_id
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public Long getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.chat_id
     *
     * @param chatId the value for v_chat.chat_id
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.userid_from
     *
     * @return the value of v_chat.userid_from
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public Long getUseridFrom() {
        return useridFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.userid_from
     *
     * @param useridFrom the value for v_chat.userid_from
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setUseridFrom(Long useridFrom) {
        this.useridFrom = useridFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.userid_to
     *
     * @return the value of v_chat.userid_to
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public Long getUseridTo() {
        return useridTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.userid_to
     *
     * @param useridTo the value for v_chat.userid_to
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setUseridTo(Long useridTo) {
        this.useridTo = useridTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.message_content
     *
     * @return the value of v_chat.message_content
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.message_content
     *
     * @param messageContent the value for v_chat.message_content
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.createtime
     *
     * @return the value of v_chat.createtime
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.createtime
     *
     * @param createtime the value for v_chat.createtime
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.from_username
     *
     * @return the value of v_chat.from_username
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public String getFromUsername() {
        return fromUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.from_username
     *
     * @param fromUsername the value for v_chat.from_username
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setFromUsername(String fromUsername) {
        this.fromUsername = fromUsername == null ? null : fromUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.from_avatar
     *
     * @return the value of v_chat.from_avatar
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public String getFromAvatar() {
        return fromAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.from_avatar
     *
     * @param fromAvatar the value for v_chat.from_avatar
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setFromAvatar(String fromAvatar) {
        this.fromAvatar = fromAvatar == null ? null : fromAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.to_username
     *
     * @return the value of v_chat.to_username
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public String getToUsername() {
        return toUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.to_username
     *
     * @param toUsername the value for v_chat.to_username
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setToUsername(String toUsername) {
        this.toUsername = toUsername == null ? null : toUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.to_avatar
     *
     * @return the value of v_chat.to_avatar
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public String getToAvatar() {
        return toAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.to_avatar
     *
     * @param toAvatar the value for v_chat.to_avatar
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setToAvatar(String toAvatar) {
        this.toAvatar = toAvatar == null ? null : toAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.readed
     *
     * @return the value of v_chat.readed
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public Integer getReaded() {
        return readed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.readed
     *
     * @param readed the value for v_chat.readed
     *
     * @mbg.generated Fri Apr 07 01:04:13 CST 2023
     */
    public void setReaded(Integer readed) {
        this.readed = readed;
    }
}