package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class VChat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.chat_id
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private Long chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.userid_from
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private Long useridFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.userid_to
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private Long useridTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.message_content
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private String messageContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.createtime
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.from_username
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private String fromUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_chat.from_avatar
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    private String fromAvatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.chat_id
     *
     * @return the value of v_chat.chat_id
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public Long getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.chat_id
     *
     * @param chatId the value for v_chat.chat_id
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.userid_from
     *
     * @return the value of v_chat.userid_from
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public Long getUseridFrom() {
        return useridFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.userid_from
     *
     * @param useridFrom the value for v_chat.userid_from
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setUseridFrom(Long useridFrom) {
        this.useridFrom = useridFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.userid_to
     *
     * @return the value of v_chat.userid_to
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public Long getUseridTo() {
        return useridTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.userid_to
     *
     * @param useridTo the value for v_chat.userid_to
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setUseridTo(Long useridTo) {
        this.useridTo = useridTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.message_content
     *
     * @return the value of v_chat.message_content
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.message_content
     *
     * @param messageContent the value for v_chat.message_content
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.createtime
     *
     * @return the value of v_chat.createtime
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.createtime
     *
     * @param createtime the value for v_chat.createtime
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.from_username
     *
     * @return the value of v_chat.from_username
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public String getFromUsername() {
        return fromUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.from_username
     *
     * @param fromUsername the value for v_chat.from_username
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setFromUsername(String fromUsername) {
        this.fromUsername = fromUsername == null ? null : fromUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_chat.from_avatar
     *
     * @return the value of v_chat.from_avatar
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public String getFromAvatar() {
        return fromAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_chat.from_avatar
     *
     * @param fromAvatar the value for v_chat.from_avatar
     *
     * @mbg.generated Sun Apr 02 13:00:30 CST 2023
     */
    public void setFromAvatar(String fromAvatar) {
        this.fromAvatar = fromAvatar == null ? null : fromAvatar.trim();
    }
}