package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class VComment {
    /**
     * 评论id
     * 此字段对应于数据库列v_comment.comment_id
     */
    private Long commentId;

    /**
     * 评论内容
     * 此字段对应于数据库列v_comment.comment_content
     */
    private String commentContent;

    /**
     * 评论所属博客id
     * 此字段对应于数据库列v_comment.blog_id
     */
    private Long blogId;

    /**
     * 评论时间
     * 此字段对应于数据库列v_comment.createtime
     */
    private Date createtime;

    /**
     * 评论者id
     * 此字段对应于数据库列v_comment.userid
     */
    private Long userid;

    /**
     * 评论者用户名
     * 此字段对应于数据库列v_comment.username
     */
    private String username;

    /**
     * 评论者用户头像
     * 此字段对应于数据库列v_comment.avatar
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.comment_id
     *
     * @return the value of v_comment.comment_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.comment_id
     *
     * @param commentId the value for v_comment.comment_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column
     * v_comment.comment_content
     *
     * @return the value of v_comment.comment_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.comment_content
     *
     * @param commentContent the value for v_comment.comment_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.blog_id
     *
     * @return the value of v_comment.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.blog_id
     *
     * @param blogId the value for v_comment.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.createtime
     *
     * @return the value of v_comment.createtime
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.createtime
     *
     * @param createtime the value for v_comment.createtime
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.userid
     *
     * @return the value of v_comment.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.userid
     *
     * @param userid the value for v_comment.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.username
     *
     * @return the value of v_comment.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.username
     *
     * @param username the value for v_comment.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.avatar
     *
     * @return the value of v_comment.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.avatar
     *
     * @param avatar the value for v_comment.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}