package com.xftxyz.rocketblog.pojo;

import java.util.Date;

public class VComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.comment_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.comment_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.createtime
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_comment.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.comment_id
     *
     * @return the value of v_comment.comment_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.comment_id
     *
     * @param commentId the value for v_comment.comment_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.comment_content
     *
     * @return the value of v_comment.comment_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.comment_content
     *
     * @param commentContent the value for v_comment.comment_content
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.blog_id
     *
     * @return the value of v_comment.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.blog_id
     *
     * @param blogId the value for v_comment.blog_id
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.createtime
     *
     * @return the value of v_comment.createtime
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.createtime
     *
     * @param createtime the value for v_comment.createtime
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.userid
     *
     * @return the value of v_comment.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.userid
     *
     * @param userid the value for v_comment.userid
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.username
     *
     * @return the value of v_comment.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.username
     *
     * @param username the value for v_comment.username
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_comment.avatar
     *
     * @return the value of v_comment.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_comment.avatar
     *
     * @param avatar the value for v_comment.avatar
     *
     * @mbg.generated Sat Apr 01 15:13:18 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}