name: 构建和部署

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 设置 Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 安装依赖项
        run: |
          cd vueblog
          npm install

      - name: 构建 Vue.js 应用程序
        run: |
          cd vueblog
          npm run build

      - name: 复制文件
        run: cp -rf vueblog/dist/. rocketblog/src/main/resources/static/

      - name: 构建Spring Boot应用程序
        run: |
          cd rocketblog
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: 部署到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./rocketblog/target/rocketblog-0.0.1-SNAPSHOT.jar
          target: /root/

      - name: 在服务器上启动应用程序
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source /etc/profile
            PID=$(ps -ef | grep rocketblog-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{ print $2 }')
            if [ -z "$PID" ]
            then
              echo Application is already stopped
            else
              echo kill -9 $PID
              kill -9 $PID
            fi
            nohup java -jar rocketblog/target/rocketblog-0.0.1-SNAPSHOT.jar >> bloglog &
