name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          cd vueblog
          npm install

      - name: Build Vue.js app
        run: |
          cd vueblog
          npm run build

      - name: Build Spring Boot app
        run: |
          cd rocketblog
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Clean up old files
        run: |
          cd rocketblog/src/main/resources
          rm -rf static

      - name: Copy new files
        run: |
          cd vueblog/dist
          cp -R . ../../rocketblog/src/main/resources/static/

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "rocketblog/target/rocketblog-0.0.1-SNAPSHOT.jar,start.sh"
          target: /root

      - name: Start application on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source /etc/profile
            chmod +x start.sh
            ./start.sh
